apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-custom-exporter
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-custom-exporter
    app.kubernetes.io/component: exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-custom-exporter
  labels:
    app.kubernetes.io/name: argocd-custom-exporter
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-custom-exporter
  labels:
    app.kubernetes.io/name: argocd-custom-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-custom-exporter
subjects:
  - kind: ServiceAccount
    name: argocd-custom-exporter
    namespace: argocd
