apiVersion: v1
kind: Service
metadata:
  name: argocd-custom-exporter
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-custom-exporter
    app.kubernetes.io/component: exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9184
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-custom-exporter
